import type {ButtonHTMLAttributes,InputHTMLAttributes,ReactNode} from 'react';import {X} from 'lucide-react';
const cn=(...v:(string|false|undefined|null)[])=>v.filter(Boolean).join(' ');
export function Logo({light=false}:{light?:boolean}){return <div className="logo"><span className={cn('logo-mark',light&&'light')}>B<span>✦</span></span><strong className={light?'text-white':''}>bookeasy</strong></div>}
export function Button({className='',variant='primary',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'}){return <button className={cn('btn',`btn-${variant}`,className)} {...props}/>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'brand'}){return <span className={cn('badge',`badge-${tone}`)}>{children}</span>}
export function Avatar({name,color='#6e3d57',size='md'}:{name:string;color?:string;size?:'sm'|'md'|'lg'}){const initials=name.split(' ').map(x=>x[0]).join('').slice(0,2);return <span className={cn('avatar',`avatar-${size}`)} style={{background:color}} aria-label={name}>{initials}</span>}
export function Field({label,error,...props}:InputHTMLAttributes<HTMLInputElement>&{label:string;error?:string}){return <label className="field"><span>{label}</span><input {...props}/>{error&&<small>{error}</small>}</label>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){if(!open)return null;return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><header><div><small>BOOKEASY</small><h2>{title}</h2></div><button className="icon-btn" onClick={onClose} aria-label="Close"><X size={18}/></button></header>{children}</section></div>}
export function Empty({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>}
